# Generated by Django 3.2 on 2021-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0003_alter_register_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='用户编号'),
        ),
    ]
