# Generated by Django 3.2 on 2021-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0003_alter_register_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='取药单编号'),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='补货时间'),
        ),
    ]
