# Generated by Django 3.2 on 2021-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=11, verbose_name='年龄'),
        ),
    ]
