# Generated by Django 3.2 on 2021-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(max_length=19, verbose_name='身份证号'),
        ),
    ]
