# Generated by Django 3.2 on 2021-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0006_alter_patient_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户编号'),
        ),
    ]
