# Generated by Django 3.2 on 2021-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id_number',
            field=models.CharField(max_length=19, verbose_name='身份证号'),
        ),
    ]
