# Generated by Django 3.2 on 2021-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0008_alter_doctor_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='取药时间'),
        ),
    ]
